# Name of the project
PROJECT_NAME = phone_book

#Doxyfile folder
DOC = documentation

#All source code files
SRC = phonebook.c\
src/phone_operations.c

#All test source files
TEST_SRC = src/phone_operations.c\
test/test_phone_operations.c\
unity/unity.c

TEST_OUTPUT = Test_a.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = phonebook.exe

#Document files
DOCUMENTATION_OUTPUT = documentation/html


Build:
	gcc function1.c test_phonebook.c unity/unity.c -Iunity

Run:
	./a.out